mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'
urlpatterns=[
    url(r'^$',views.index,name="index"),
    url('marble/',views.marble,name="marble"),
    url('wishlist/',views.wishlist,name="wishlist"),
    url('vote/',views.vote,name="vote"),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

mysite/polls/views.py
from django.template.loader import render_to_string
from django.conf import settings
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Question,Choice
from django.core.mail import EmailMessage
from django.core.mail import send_mail

# Create your views here.

html_content=''

def index(request):
    #return HttpResponse(template.render(context,request))
    return render(request,'polls/index.html')


def marble(request):
    #return HttpResponse(template.render(context,request))
    return render(request,'polls/marbles.html')

def wishlist(request):
    for name,value in request.COOKIES.items():
        print ("key:"+name)
        print ("value:"+value)
    html_content=render_to_string('polls/wishlist.html',{'cookies':request.COOKIES})
    html_content=render(request,'polls/wishlist.html',{'cookies':request.COOKIES})
    return html_content

def vote(request):
    to=request.POST['choice']
    print(to)
    #send_mail(
    #'Subject here',
    #'Here is the message.',
    #'devsharmarouth132@gmail.com',
    #[to],
    #fail_silently=False,
    #)
    #rendered = render_to_string('polls/wishlist.html')
    #html_content=rendered
    html_content=render_to_string('polls/wishlist.html',{'cookies':request.COOKIES})   
    
    
    msg = EmailMessage('email fro arm', html_content,'devsharmarouth132@gmail.com', [to])
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()
    return HttpResponseRedirect(reverse('polls:wishlist'))
    
    

mysite/polls/templates/polls/index.html
{%load static %}
<head>
<title>ARUNA GRANITE AND MARBLES</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Today Flats Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'polls/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'polls/css/style.css' %}" rel='stylesheet' type='text/css' /> 
<link rel="stylesheet" href="{% static 'polls/css/smoothbox.css' %}" type='text/css' >
<!-- //Custom Theme files -->
<!-- js -->
<script src="{% static 'polls/js/jquery.min.js' %}"></script>
<!-- //js -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //web font -->
</head>
<body> 
	
		
			<div class="navigation">
				<div class="container">
					<div class="agileits-logo">
						<h1><a href="">ARUNA <span class="w3agile">GRANITE AND MARBLES</span></a></h1>
					</div>
					<div class="navigation-right">
						<span class="menu"><img src="{% static 'polls/images/menu.png' %}" alt=" " /></span>
						<nav class="link-effect-3" id="link-effect-3">
							<ul class="nav1 nav">
								<li class="active"><a data-hover="Home" href="">Home</a></li>
								<li><a href="#about" class="scroll" data-hover="About">About</a></li>
								<li><a href="#agents" class="scroll" data-hover="Products">Products</a></li> 
			<!--					<li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" data-hover="Pages">Pages <span class="caret"></span></a>
									<ul class="dropdown-menu"> 
										<li><a data-hover="Gallery" href="#gallery" class="scroll">Gallery</a></li>
										<li><a data-hover="Testimonials" href="#testimonial" class="scroll">Testimonials</a></li>
									</ul>
								</li>  -->
								<li><a data-hover="Contact" href="#contact" class="scroll">Contact</a></li>
							</ul>
						</nav>
							<!-- script-for-menu -->
							<script>
							   $( "span.menu" ).click(function() {
								 $( "ul.nav1" ).slideToggle( 300, function() {
								 // Animation complete.
								  });
								 });
							</script>
							<!-- //script-for-menu -->
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			
				

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
        <div id="main-container" class="container">
     <div class="jumbotron">
    <div class="carousel-inner" role="listbox">
     <div class="item active">
       <img src="{% static 'polls/images/s1.jpg' %}" alt="...">
       <div class="carousel-caption">
        ...
       </div>
     </div>
     <div class="item">
       <img src="{% static 'polls/images/s2.jpg' %}" alt="...">
       <div class="carousel-caption">
        ...
       </div>
     </div>
    ...
    </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    </div>
        </div>
        
	<!-- team -->
	<div class="team" id="agents">
		<div class="container">
			<h3>OUR CATEGORIES</h3>
			<div class="agile_team_grids">
				<div class="col-md-3 agile_team_grid">
					<div class="view w3-agile-view">
						<img src="{% static 'polls/images/limestone.jpg' %}" alt=" " class="img-responsive" />
						<div class="w3lmask">
							<h5>Lime Stone</h5>
							<p>Limestone often contains variable amounts of silica in the form of chert and/or flint, as well as varying amounts of clay, silt and sand as disseminations, nodules, or layers within the rock.</p>
						
						</div>
					</div>
					<h4>Lime Stone</h4>
					
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="view w3-agile-view">
						<img src="{% static 'polls/images/sandstone.jpg' %}" alt=" " class="img-responsive" />
						<div class="w3lmask">
							<h5>Stand Stone</h5>
							<p>Sandstone is a sedimentary rock composed mainly of sand-size mineral or rock grains. Most sandstone is composed of quartz and/or feldspar because these are the most common minerals in the Earth's crust.</p>
							
						</div>
					</div>
					<h4>Stand Stone</h4>
                    
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="view w3-agile-view">
                        <a href="{% url 'polls:marble' %}"><img href="{% url 'polls:marble' %}" src="{% static 'polls/images/marbles.jpg' %}" alt=" " class="img-responsive"></a>
						<a href="{% url 'polls:marble' %}"><div class="w3lmask">
							<h5>Marbles</h5>
							<p>Marble is a non foliated metamorphic rock. It is extensively used for sculpture, as a building material, and in many other applications. Marbles are capable of taking a high polish.</p>
						
                            </div></a>
					</div>
					<h4>Marbles</h4>
					
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="view w3-agile-view">
						<img src="{% static 'polls/images/granites.jpg' %}" alt=" " class="img-responsive" />
						<div class="w3lmask">
							<h5>Granites</h5>
							<p>Granite is a common occurring type of intrusive, felsic, igneous rock.Granite is nearly always massive, hard and tough, and therefore it has gained widespread use as a construction stone. The average density of granite is 2.75 g/cm3 </p>
               			</div>
					</div>
					<h4>Granites</h4>
					
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	
	<!-- contact -->
	<div class="contact" id="contact">
		<div style="background-color:#ADD8E6; padding:40px 40px 40px 40px">
			<h3><a href="index.html">Aruna Granite and Marbles </a></h3>
			<div class="col-xs-6 w3agile_contact_right_agileinfo">
				<h4>Address</h4>
				<p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>E-275, Aruna Granite and Marbles,M.I.A, Basni, IInd Phase, Jodhpur, Rajasthan</p>
				<p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>(+) 91 9414130162</p>
				<p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:arunagraniteandmarbles@gmail.com">arunagraniteandmarbles@gmail.com</a></p>
			</div>
			<div class="col-xs-6 w3agile_contact_right_agileinfo">
				<h4>Follow Us</h4>
				<div class="agileits_social_icons">
					<a href="#" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
					<a href="#" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
					<a href="#" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
				</div>
			</div>
			<div class="clearfix"> </div>
			<div class="w3_copy_right">
				<p>© 2017 Aruna Granite and Marbles . All rights reserved.<i>Design by Himanshu Mehta And Dev Sharma</i>                                                                            </p>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- //contact -->
	<!-- bootstrap js -->
	<script src="{% static 'polls/js/bootstrap.js' %}"></script>
	<!-- //bootstrap js -->
	<!-- start-smooth-scrolling -->
	<script type="text/javascript" src="{% static 'polls/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'polls/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- start-smooth-scrolling -->
	<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
	<!-- //here ends scrolling icon -->
</body>

mysite/polls/templates/polls/marbles.html
{%load static %}
<head>
<title>ARUNA GRANITE AND MARBLES</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Today Flats Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'polls/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'polls/css/style.css' %}" rel='stylesheet' type='text/css' /> 
<link rel="stylesheet" href="{% static 'polls/css/smoothbox.css' %}" type='text/css' >
<!-- //Custom Theme files -->
<!-- js -->
<script type="text/javascript" src="{% static 'polls/js/cookies.js' %}"></script>

<script src="{% static 'polls/js/jquery.min.js' %}"></script>
    
<script type="text/javascript">
    function checkCookie() {
    var no=getCookie("no");
    if (no != "") {
        document.getElementById("no_of_products").textContent=no;
    } else {
       document.getElementById("no_of_products").textContent=0;
    }
}
</script>
<!-- //js -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //web font -->
</head>
<body onload="checkCookie()"> 
	
		
			<div class="navigation">
				<div class="container">
					<div class="agileits-logo">
						<h1><a href="index.html">ARUNA <span class="w3agile">GRANITE AND MARBLES</span></a></h1>
					</div>
					<div class="navigation-right">
						<span class="menu"><img src="{% static 'polls/images/menu.png' %}" alt=" " /></span>
						<nav class="link-effect-3" id="link-effect-3">
							<ul class="nav1 nav">
								<li><a data-hover="Home" href="{% url 'polls:index' %}">Home</a></li>
								<li><a href="#about" class="scroll" data-hover="About">About</a></li>
								<li class="active"><a href="#agents" class="scroll" data-hover="Products">Products</a></li> 
				<!--				<li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" data-hover="Pages">Pages <span class="caret"></span></a>
									<ul class="dropdown-menu"> 
										<li><a data-hover="Gallery" href="#gallery" class="scroll">Gallery</a></li>
										<li><a data-hover="Testimonials" href="#testimonial" class="scroll">Testimonials</a></li>
									</ul>
								</li>-->  
								<li><a data-hover="Contact" href="#contact" class="scroll">Contact</a></li>
							</ul>
						</nav>
							<!-- script-for-menu -->
							<script>
							   $( "span.menu" ).click(function() {
								 $( "ul.nav1" ).slideToggle( 300, function() {
								 // Animation complete.
								  });
								 });
							</script>
							<!-- //script-for-menu -->
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
    
        <div style="margin:20px 20px 20px 20px" class="container">
            <div class="row">
                <div class="col-md-2">
                  <div class="panel panel-default">
                    <div class="panel-heading"><h4>WishList</h4></div>
                       <a href="{% url 'polls:wishlist' %}" class="panel-body">Products<span id="no_of_products" class="badge">0</span></a>
                    </div>
                </div>
                <div class="col-md-10">
                  <img src="{% static 'polls/images/marble_page.jpg' %}"/>
                  <p>Marble is a non foliated metamorphic rock. It is extensively used for sculpture, as a building material, and in many other applications. Marbles are capable of taking a high polish.</p>  
                  <hr> 
                  <h3>SubCateogories</h3>
                  <div class="row">
                    <div class="col-md-3">
                       <div class="thumbnail">
                         <img src="{% static 'polls/images/rain_forest_golden.jpg' %}" alt="...">
                          <div class="caption">
                             <h4>Rain Forest Golden</h4>
                                <p><a href="#" class="btn btn-default btn-log" data-toggle="modal" data-target="#myModal1" role="button">View</a> <a href="#" class="btn btn-default"  role="button" onclick="createCookie('Rain Forest Golden','{% static 'polls/images/rain_forest_golden.jpg' %}')">Add To WishList</a></p>
                         </div>
                       </div>
                        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                         <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <img src="{% static 'polls/images/rain_forest_golden_xl.jpg' %}">

                          </div>
                         </div>
                        </div>
                      </div>
                       <div class="col-md-3">
                       <div class="thumbnail">
                         <img src="{% static 'polls/images/rain_forest_green.jpg' %}" alt="...">
                          <div class="caption">
                             <h4>Rain Forest Green</h4>
                                <p><a href="#" class="btn btn-default btn-log" data-toggle="modal" data-target="#myModal2" role="button">View</a> <a href="#" class="btn btn-default"  role="button" onclick="createCookie('Rain Forest Green','{% static 'polls/images/rain_forest_green.jpg' %}')">Add To WishList</a></p>
                         </div>
                       </div>
                        <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                         <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <img src="{% static 'polls/images/rain_forest_green_xl.jpg' %}">

                          </div>
                         </div>
                        </div>
                      </div>
                       <div class="col-md-3">
                       <div class="thumbnail">
                         <img src="{% static 'polls/images/rain_forest_brown.jpg' %}" alt="...">
                          <div class="caption">
                             <h4>Rain Forest Brown</h4>
                                <p><a href="#" class="btn btn-default btn-log" data-toggle="modal" data-target="#myModal3" role="button">View</a> <a href="#" class="btn btn-default"  role="button" onclick="createCookie('Rain Forest Brown','{% static 'polls/images/rain_forest_brown.jpg' %}')">Add To WishList</a></p>
                         </div>
                       </div>
                        <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                         <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <img src="{% static 'polls/images/rain_forest_brown_xl.jpg' %}">

                          </div>
                         </div>
                        </div>
                      </div>
                       <div class="col-md-3">
                       <div class="thumbnail">
                         <img src="{% static 'polls/images/pink_marble.jpg' %}" alt="...">
                          <div class="caption">
                             <h4>Pink Marble</h4>
                                <p><a href="#" class="btn btn-default btn-log" data-toggle="modal" data-target="#myModal4" role="button">View</a> <a href="#" class="btn btn-default"  role="button" onclick="createCookie('Pink Marble','{% static 'polls/images/pink_marble.jpg' %}')">Add To WishList</a></p>
                         </div>
                       </div>
                        <div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                         <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <img src="{% static 'polls/images/pink_marble_xl.jpg' %}">

                          </div>
                         </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
				

  

	
	<!-- contact -->
	<div class="contact" id="contact">
		<div style="background-color:#ADD8E6; padding:40px 40px 40px 40px">
			<h3><a href="index.html">Aruna Granite and Marbles </a></h3>
			<div class="col-xs-6 w3agile_contact_right_agileinfo">
				<h4>Address</h4>
				<p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>E-275, Aruna Granite and Marbles,M.I.A, Basni, IInd Phase, Jodhpur, Rajasthan</p>
				<p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>(+) 91 9414130162</p>
				<p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:arunagraniteandmarbles@gmail.com">arunagraniteandmarbles@gmail.com</a></p>
			</div>
			<div class="col-xs-6 w3agile_contact_right_agileinfo">
				<h4>Follow Us</h4>
				<div class="agileits_social_icons">
					<a href="#" class="icon-button twitter"><i class="icon-twitter"></i><span></span></a>
					<a href="#" class="icon-button facebook"><i class="icon-facebook"></i><span></span></a>
					<a href="#" class="icon-button google-plus"><i class="icon-google-plus"></i><span></span></a>
				</div>
			</div>
			<div class="clearfix"> </div>
			<div class="w3_copy_right">
				<p>© 2017 Aruna Granite and Marbles . All rights reserved.<i>Design by Himanshu Mehta And Dev Sharma</i>                                                                            </p>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- //contact -->
	<!-- bootstrap js -->
	<script src="{% static 'polls/js/bootstrap.js' %}"></script>
	<!-- //bootstrap js -->
	<!-- start-smooth-scrolling -->
	<script type="text/javascript" src="{% static 'polls/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'polls/js/easing.js' %}"></script>
	<!--<script type="text/javascript" src="{% static 'polls/js/cookies.js' %}"></script>-->
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- start-smooth-scrolling -->
	<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
	<!-- //here ends scrolling icon -->
</body>